### ISSUE TITLE
transaction support...

### ISSUE THREAD

**Issue by freeeve** [AnormCypher/AnormCypher#15]
http://docs.neo4j.org/chunked/preview/rest-api-transactional.html

**Comment by Kai-Chen** [comment]
### Architectural Concerns

Existing Java libraries for Transaction are not immediately usable, as all the ones that I looked at store Transaction details in a ThreadLocal object.  While this would work in a thread-per-request environment common in JEE containers, in an asynchronous environment like Play, where the same thread could end up serving multiple on-going requests, this would cause problems.

The standard Scala approach would be using an implicit parameter for Transaction-aware connections with the Loan pattern.  The advantage is that we get to keep asynchronous processing; the disadvantage is that it won't fit into something like the Spring Framework.  To address the second part, though. writing an adapter, or even an JTA wrapper, should not be a show-stopper as we can always give up asynchronous and block in environments that don't mind blocking IO, thus falling back to ThreadLocal-based mechanisms.

### Backwards Compatibility
The tougher part is to keep the current API working, because the Neo4j endpoints are different for transactions.  On top of that, the JSON response is also slightly different.  So we might have to have a separate API for transactional statements.  This will be the first attempt at least.

**Comment by freeeve** [comment]
What about the new protocol? There's actually a java library by Neo that provides a socket/stream per session. Not sure if that would work... Definitely faster than json. https://github.com/neo4j/neo4j-java-driver

**Comment by Kai-Chen** [comment]
Looks nice!  It's in anticipation of the 3.0 release, though.  I like the JDBC-like API, and I suppose once it's solid enough, AnormCypher can just slim down to a thin wrapper of it for Scala :)  Kinda makes me wonder if it might be better to just wait.  On the other hand, I do need to have the transaction feature now, not a couple of months later.  Hmmm :)

The syntax work is going to be necessary anyway.  So that part is not a throw-away.

**Comment by Kai-Chen** [comment]
### Backwards Compatibility
The current CypherStatement APIs will be transparently moved to using the transaction endpoint.  Each statement will execute in a single-request, auto-commit transaction.

Error handling gets a bit tricky as the server no longer sends HTTP error codes but streams all results, including error, in a 200 response.  See commit  4bff4a1.

NeoNode and NeoRelationship mapping will be changed to using the new plain json format returned from the tx endpoint.  Even with the `'resultDataContents' : [ 'REST' ]` in the request body, if a node is returned along with a projection, the plain json format is always used.  So one would not be able to get the meta data unless the Cypher statement specifically returns only nodes, relationships.
