### ISSUE TITLE
Upload latest version to maven repository

### ISSUE THREAD

**Issue by alexd6631** [AnormCypher/AnormCypher#46]
Hello,

I am really interested in using Async support introduced in 37342c9e936b243bc2528568eb1170dbad4d8cb3 to use AnormCypher as a non blocking driver.
The 0.6.0 version does not include async support.

Any chance you could upload it to your maven repository ?

**Comment by felixmulder** [comment]
For now, I use wrappers to make this library async - but I would too be interested in a release of the updated lib!

**Comment by Kai-Chen** [comment]
0.7 (due end of October) should have the async support, and when it's ready, Eve will publish it.

Note also that, the specific API will be changed in 0.8, since Future[Stream] isn't quite the right way to approach it.  There will be 2 async methods instead, one that would return a Future[Seq], which is what async() returns, and another would return an Enumerator, which allows streaming very large response bodies.

**Comment by Kai-Chen** [comment]
Latest release 0.7.1 (for Play 2.4) and 0.7.0 (for Play 2.3) both have async support.
