### ISSUE TITLE
Add Play 2.5 support

### ISSUE THREAD

**Issue by EhsanYousefi** [AnormCypher/AnormCypher#52]
It seems AnormCypher doesn't work with Play 2.5,

I got this error while compiling Play:
`
Error:(12, 35) could not find implicit value for parameter materializer: akka.stream.Materializer
  val wsclient = ning.NingWSClient()
                                  ^
`

**Comment by Kai-Chen** [comment]
Just to get some more info:

Your project depends on AnormCypher and Play among others.  When you compile it with AnormCypher 0.8.1 and Play 2.5, you get a compiler error.

Is that correct?

If you are using Play, you really should inject an instance of WSClient into your app and also into Neo4jREST by providing an implicit instance of it, instead of creating one on your own, unless you have a good reason to.  HTH.

**Comment by Kai-Chen** [comment]
Closing this as there is no user response.  Probably same cause as issue #54
